version: "3"

networks:
    inception:
        driver: bridge

volumes:
    mariadb:
        driver_opts:
            type: none
            o: bind
            device: $MARIADB_VOLUME_PATH

  
    wordpress:
        driver_opts:
            type: none
            o: bind
            device: $WORDPRESS_VOLUME_PATH


services:
    mariadb:
        image: mariadb
        container_name: mariadb
        build:
            context: ./requirements/mariadb/.
        expose:
            - $MARIADB_PORT
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - mariadb:/var/lib/mysql/
        restart: on-failure
    
    nginx:
        image: nginx
        container_name: nginx
        build:
            context: ./requirements/nginx/.
        expose:
            - $NGINX_PORT
        ports:
            - $NGINX_PORT:$NGINX_PORT
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - wordpress:/var/www/html/
        restart: on-failure
        depends_on:
            - wordpress

    wordpress:
        image: wordpress
        container_name: wordpress
        build:
            context: ./requirements/wordpress/.
        expose:
            - $WORDPRESS_PORT
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - wordpress:/var/www/html/
        restart: on-failure
        depends_on:
            - mariadb
    